In [24]:
# If outlier data is obtained then we will use median else mean(e.g.: age: 1,2,3,four,5,6) --> outlier will be four because all are int and four is string
# for month type we fill the null values with mode, because here mean and median will not work
# we use mean, median and mode to fill the null value

# LIST COMPREHENSION #
list_of_num = [1,2,3,4,5]
k = []
# for i in list_of_num:
  # k.append(i*i)

# print(k)

# k = [i**2 for i in list_of_num]
# print(k)

## list comprehension
l = [i**2 if(i%2==0) else i**3 for i in list_of_num]
print("The list of numbers: ",l)


The list of numbers:  [1, 4, 27, 16, 125]


In [61]:
sentence = "Hello everyone! what are you doing? I am going to trekking."
l = {i[0] for i in sentence.split()}
print(l)


{'y', 'g', 'd', 'H', 't', 'w', 'e', 'a', 'I'}


In [98]:
########## FUNCTIONS ########
num = 10
fact = 1
for i in range(1,num+1):
  fact*=i
print(fact)


# def(arg1, arg2, .....):
# code
# return value

def fact(n):
  fact = 1
  for i in range(1,n+1):
    fact*=i
  return fact
fact(10)

3628800


3628800

In [2]:
# sample_date = '2020-07-01'
def datequarter(sample_date):
  temp = int(sample_date.split("-")[1])
  if(temp<=3):
    print('Quarter 1')
  elif(temp>3 and temp <=6):
    print('Quarter 2')
  elif(temp>6 and temp<=9):
    print('Quarter 3')
  elif(temp>9 and temp<=12):
    print('Quarter 4')
  else:
    return 'Invalid'
sample_date = input("Enter date: yyyy-mm-dd")
print(datequarter(sample_date))

# def datequarter(sample_date):
#   temp = int(sample_date.split("-")[1])
#   print(temp)
#   if temp < 4:
#     print('Quarter 1')
#   elif temp >3 & temp <7:
#     print('Quarter 2')
#   elif temp>6 & temp<=9:
#     print('Quarter 3')
#   elif temp>9 & temp<=12:
#     print('Quarter 4')
#   else:
#     return 'Invalid'
# sample_date = input("Enter date: yyyy-mm-dd")
# print(datequarter(sample_date))

Enter date: yyyy-mm-dd2025-09-08
Quarter 3
None


In [147]:
a = [1,2,3,4,5,6]
value = 100
index = 3

# def addval(value,index):
a = a[0:index-1] + [value] + a[index+1:]
  # return L1
print(a)

# addval(100,3)



[1, 2, 3, 100, 4, 5, 0]


In [150]:
a = [1,2,3,4,5,]
def f():
  b = [0]
  a.extend(b)
for i in range(len(a)-1,index-1,-1):
  a[i] = a[i-1]
a[3] = 100

f()
print(a)

[1, 2, 3, 100, 4, 5, 0]


In [156]:
###### OOPS ######
class bpit:
  def __init__(self,name,age):
    self.name = name
    self.age = age
  def student_name(self):
    print(f"this is class bpit and student name is: {self.name}")
  def student_age(self):
    print(f"this is class bpit and student age is: {self.age}")

obj = bpit('raghav',10)
obj.student_name()
obj.student_age()


class radius:
  def __init__(self,r):
    self.r = r
  def circle(self):
    print(3.14*self.r*self.r)
obj = radius(10)
obj.circle()

this is class bpit and student name is: raghav
this is class bpit and student age is: 10
314.0


In [1]:
a = "name"
try:
  print(abc)
except:
  print("Invalid")

Invalid


In [33]:
##################### NUMPY ####################
# functionality is more in numpy
# reduced time and space complexity


# keyword module alias
import numpy as np
a = np.array([1,2,3,4]) # 1-d array
type(a) # list has commas in between them whereas array don't have

numpy.ndarray

In [34]:
print(a) # shape(column)

[1 2 3 4]


In [35]:
a.shape

(4,)

In [37]:
a = np.array([[1,2],[3,4]])
print(a) # shape(row,column)

[[1 2]
 [3 4]]


In [38]:
a.shape

(2, 2)

In [39]:
a = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [40]:
a.shape  # shape(sub-array,row,column)

(1, 4, 2)

In [41]:
a = np.array([1,2,3,4]) # 1-d array
print(a.ndim)

1


In [42]:
a = np.array([[1,2],[3,4]])
print(a.ndim)

2


In [45]:
a = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(a.ndim)
print(a.shape)
print(a.size)

3
(1, 4, 2)
8


In [60]:
a = np.array([1,2,3,4])
print(a.dtype)

int64


In [47]:
a = np.array([1.0,2.0,3.0,4.0])
print(a.dtype)

float64


In [57]:
a = np.array(['1','2'])
b = np.array(['aa','111','12','kasj']) # largest is returned
print(a.dtype)
print(b.dtype)

<U1
<U4


In [69]:
# a.astype('float64')
a.astype('int64')
b.astype('<U4')

array(['aa', '111', '12', 'kasj'], dtype='<U4')

In [71]:
a = np.zeros([3,4],dtype = 'int64')
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [67]:
a = np.ones([3,4],dtype = 'int64')
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [74]:
a = np.zeros([3,4],dtype = 'int64')
# print(a)
print(a+30)

[[30 30 30 30]
 [30 30 30 30]
 [30 30 30 30]]


In [89]:
# array from random numbers
a = np.random.randint(10,15,(2,3,4))
print(a)

[[[12 13 14 13]
  [10 14 14 10]
  [14 12 11 14]]

 [[13 11 14 14]
  [10 10 11 14]
  [10 11 14 10]]]


In [90]:
# Slicing 1-d array
# a['columns']

# slicing 2-d array
# a['row','column']

#slicing 3-d array
# a['sub-array','row',column]

In [91]:
a = np.array([1,2,3,4])
print(a[0])

1


In [104]:
a = np.random.randint(10,15,(2,3,4))
print(a)
# print(a[1,1,1])
# print(a[1,-2,-2])

[[[11 11 14 10]
  [12 13 13 12]
  [12 11 10 10]]

 [[13 10 14 14]
  [10 10 13 13]
  [14 12 13 12]]]


In [100]:
a = np.random.randint(10,15,(2,3))
print(a[0][1])
print(a)

14
[[13 14 10]
 [11 12 14]]


In [107]:
print(a.T) # transpose

[[[11 13]
  [12 10]
  [12 14]]

 [[11 10]
  [13 10]
  [11 12]]

 [[14 14]
  [13 13]
  [10 13]]

 [[10 14]
  [12 13]
  [10 12]]]


In [110]:
a = np.random.randint(10,15,(4,3))
print(a)

[[12 11 11]
 [13 10 11]
 [11 12 14]
 [11 13 11]]


In [112]:
print(np.reshape(a,[3,4]))

[[12 11 11 13]
 [10 11 11 12]
 [14 11 13 11]]


In [115]:
print(np.reshape(a,[3,2,2]))

[[[12 11]
  [11 13]]

 [[10 11]
  [11 12]]

 [[14 11]
  [13 11]]]


In [128]:
print(np.resize(a,[3,2,6]))

[[[12 11 11 13 10 11]
  [11 12 14 11 13 11]]

 [[12 11 11 13 10 11]
  [11 12 14 11 13 11]]

 [[12 11 11 13 10 11]
  [11 12 14 11 13 11]]]


In [132]:
# flattend to convert any array into 1-d array
print(a)

a.flatten()

[[12 11 11]
 [13 10 11]
 [11 12 14]
 [11 13 11]]


array([12, 11, 11, 13, 10, 11, 11, 12, 14, 11, 13, 11])

In [ ]:
# shallow copy-> change in copy file is affected in original file and made be reference copy
# deep copy-> change in copy file is not affected in original file and made by recursive reference of object


In [161]:
''' parse_code("john000Doe000123") -> {
    "first_name" : "John"
    "last_name" : "Doe"
    "id" : "123"
} '''
def fun(parse_code):
  strings = "john000Doe000123"
  a = strings.replace("0"," ")
  a = a.split()
  print(a)
  b = {}
  b['fname'] = a[0]
  b['lname'] = a[1]
  b['id'] = a[2]
  print(b)
fun("john000Doe000123")

['john', 'Doe', '123']
{'fname': 'john', 'lname': 'Doe', 'id': '123'}


In [171]:
a = np.random.randint(1,5,(4,5))
b = np.random.randint(10,20,(4,5))
print(a)

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a.min())
print(f"max val in array is: {a.max()}")

[[3 3 4 2 2]
 [3 2 1 1 1]
 [3 1 2 4 1]
 [1 1 4 2 1]]
[[14 17 21 17 18]
 [22 13 19 15 18]
 [21 12 15 16 19]
 [19 19 18 13 15]]
[[ -8 -11 -13 -13 -14]
 [-16  -9 -17 -13 -16]
 [-15 -10 -11  -8 -17]
 [-17 -17 -10  -9 -13]]
[[33 42 68 30 32]
 [57 22 18 14 17]
 [54 11 26 48 18]
 [18 18 56 22 14]]
[[0.27272727 0.21428571 0.23529412 0.13333333 0.125     ]
 [0.15789474 0.18181818 0.05555556 0.07142857 0.05882353]
 [0.16666667 0.09090909 0.15384615 0.33333333 0.05555556]
 [0.05555556 0.05555556 0.28571429 0.18181818 0.07142857]]
1
max val in array is: 4


In [174]:
a = np.random.randint(1,5,(4,5))
b = np.random.randint(10,20,(4,5))
print(a)
# print(a.mean())
print(f"max val in array is: {a.mean()}")

[[2 1 4 3 3]
 [1 2 2 2 2]
 [3 3 3 4 4]
 [3 2 4 4 3]]
max val in array is: 2.75


In [241]:
# anagram --> in this remove extra element to make the array same {order is not important}

a = list('cde')
b = list('dcf')
u_a = []
u_b = []
delete = []
print(a)
print(b)

for i in a:
  for j in b:
    if(a[0:len(i)-1]==b[0:len(j)-1]):
      b.pop()
      u_a.append(i)
      u_b.append(j)
      # a.pop()
    else:
      delete.remove(i)
      delete.remove(j)
print(set(u_a))
print(set(u_b))
print(a)
print(b)
print(delete)

['c', 'd', 'e']
['d', 'c', 'f']
{'c', 'd'}
{'c', 'd'}
['c', 'd', 'e']
[]
[]
